#include "arduino_secrets.h"
#include <Adafruit_Sensor.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "WeatherStationESP32"
  https://create.arduino.cc/cloud/things/79292297-8053-4971-8f89-a14b0cb3a18f 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String measurementTime;
  float humidity;
  float temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <DHT.h>
#include <time.h>

#define DHTPIN 5      // Si D5 corresponde a GPIO18
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

  dht.begin();

// Configurar hora mediante NTP
configTime(-6 * 3600, 0, "pool.ntp.org", "time.nist.gov");
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {

  ArduinoCloud.update();

  static unsigned long lastRead = 0;

  if (millis() - lastRead >= 5000) {

    lastRead = millis();

    float t = dht.readTemperature();
    float h = dht.readHumidity();

    if (!isnan(t) && !isnan(h)) {

      temperature = t;
      humidity = h;

      struct tm timeinfo;

      if (getLocalTime(&timeinfo)) {

        char fecha[30];

        strftime(fecha, sizeof(fecha), "%Y-%m-%d %H:%M:%S", &timeinfo);

        measurementTime = String(fecha);

      } else {

        measurementTime = "Sin sincronizar";

      }

      Serial.println("----------------");

      Serial.print("Temperatura: ");
      Serial.println(temperature);

      Serial.print("Humedad: ");
      Serial.println(humidity);

      Serial.print("Fecha: ");
      Serial.println(measurementTime);

    } else {

      Serial.println("Error leyendo el DHT11");

    }

  }

}




